Refs add android coding convention with Kotlin
framgia/coding-standards pull request #121
Opened 2021-01-04 10:54 UTC by longth-1474

2021-01-05 05:09 UTC, tuyenbq-0446 commented
OK

2021-01-06 07:42 UTC, ngocnd0242 commented on vn/android/coding_convention_android_kotlin.md
> +# Coding Style Guide
@longth-1474
https://github.com/framgia/coding-standards/blob/2e7e176d0fa5111fe1d0e1b67db25a92afc7dbbc/vn/android/coding_convention_android_kotlin.md
có 12 ký tự lạ � em nhé!

2021-01-06 07:47 UTC, ngocnd0242 requested changes
When viewing md file,  appeared 12 special characters �, please help me check it.

2021-01-07 02:02 UTC, longth-1474 commented
@ngocnd0242 e đã fix các kỹ thứ lạ rồi ạ. A check lại giúp e với ạ

2021-04-15 01:53 UTC, ngocnd0242 approved these changes

2021-04-16 08:48 UTC, merged